name: .NET
on:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Restore, Build, Test
      run: |
        cd Source 
        dotnet --info
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
