name: NuGet

on:
  release:
    types:
      - published

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build, Test, Pack, Push
        env:
          - NU_GET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          ./build.sh deploy
