name: NuGet

on:
  release:
    types:
      - published

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Setup .NET 6
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: 6.0.x

      - name: Build, Test, Pack, Push
        run: |
          dotnet test -c Release --verbosity quiet
          cd ./Source/MarkdownUtil
          dotnet pack -c Release
          dotnet nuget push nupkg/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
