name: NuGet Deployment

on:
  release:
    types:
      - published

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build / Test
        run: |
          cd Source
          dotnet test -c Release --verbosity quiet
          cd ./MarkdownUtil && dotnet pack -c Release

      - name: Publishing to NuGet
        run: dotnet nuget push ./MarkdownUtil/nupkg/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
